### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by sharu725** [inelaah/rain#1]
I would like to feature this theme on [jekyll-themes.com](https://jekyll-themes.com), do you have a demo link? 
I recommend using Github Pages.

**Comment by inelaah** [comment]
Hi,

Thank you. I don't have demo. Here is a live website that currently uses
Rain theme and GitHub pages: https://www.amerhukic.com/. You can use it as
an example.

**Comment by sharu725** [comment]
Thank you
